   # F-Key by thecatisbest

   # Use Sneak(Swift) + (F) key to execute commands (Use ; to make multi Commands (please don't add spaces) )
   # Player ID Placeholder: %player%
commands: "say hi;say I'm %player%"

   # Change the swap action
cancel_swap: true