name: F-Key
version: '${project.version}'
main: me.FKey.fkey
api-version: 1.13
description: When the player use Sneak+F, then send the command to player.

commands:
  FKey:
    description: View the Commands.